homeassistant:
  ## Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  ## Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 321
  ## metric for Metric, imperial for Imperial
  unit_system: imperial
  ## Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  ## Customization file
  customize: !include customize.yaml

## Show links to resources in log and frontend
introduction:

## Enables the frontend
frontend:

## Enables configuration UI
config:

http:
  ## Secrets are defined in the file secrets.yaml
  ## Enable legacy API password
  api_password: !secret ha_api_key
  ## Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: example.duckdns.org:8123

## Checks for available updates
## Note: This component will send some information about your system to
## the developers to assist with development of Home Assistant.
## For more information, please see:
## https://home-assistant.io/blog/2016/10/25/explaining-the-updater
updater:
  ## Optional, allows Home Assistant developers to focus on popular components.
  #include_used_components: true

## Discover some devices automatically
discovery:

## Allows you to issue voice commands from the frontend in enabled browsers
conversation:

## Enables support for tracking state changes over time
history:

## View all events in a logbook
logbook:

## Enables a map showing the location of tracked devices
map:

## Track the sun
sun:

## Weather prediction
sensor:
  - platform: yr

## Text to speech
tts:
  - platform: google

## Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


## Add to the side panel of home assistant
#panel_iframe:
  #hadashboard:
    #title: HA Dashboard
    #icon: mdi:view-dashboard-variant
    #url: http://0.0.0.0:5050
  #configurator:
    #title: Configurator
    #icon: mdi:circle-edit-outline
    #url: http://0.0.0.0:3218
  #tasmoadmin:
    #title: TasmoAdmin
    #icon: mdi:creation
    #url: http://0.0.0.0


## Aeotec ZW090 Z-Stick GEN5 Example for FreeNAS
## https://www.home-assistant.io/docs/z-wave/installation/#configuration
#zwave:
  #usb_path: /dev/cuaU0
  #network_key: !secret zwave_key
  #config_path: /srv/homeassistant/lib/python3.6/site-packages/python_openzwave/ozw_config
